# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
   include:
     - main
     - releases/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerfilePath: '$(System.DefaultWorkingDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  testingPipeline: 'true'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildArtifact
  displayName: "Build Artifact for Static Analaysis and Testing"
  jobs:
  - job: BuildArtifact
    displayName: "Build Artifact"
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 8.0'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        verbosityRestore: 'Normal'
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--no-restore'
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--no-build --no-restore --filter Category=Unit'
        testRunTitle: 'Register-Frontend-Unit-$(Build.BuildId)'

# Static Analysis stage: This stage runs static code analysis using SonarQube and audits dependencies for vulnerabilities.
- stage: StaticAnalysisAndAudit
  displayName: "Run Static Analysis and Audit Dependencies"
  dependsOn: BuildArtifact
  jobs:
    # SonarQube job: This job performs static code analysis using SonarQube.
    - job: SonarQube
      # condition: and(succeeded(), or(startsWith(variables['build.sourceBranch'], 'refs/heads/main'), startsWith(variables['build.sourceBranch'], 'refs/heads/dev')))
      displayName: 'Build and SonarQube Analysis'
      pool:
        vmImage: $(vmImageName)
      steps:
        # PowerShell script to modify SonarQube parameters
        - task: PowerShell@2
          displayName: "Print Branch name"
          inputs:
            targetType: 'inline'
            script: |
              echo "Branch name: $(Build.SourceBranch)"

        # Prepare SonarQube analysis
        - task: SonarQubePrepare@5
          displayName: "Prepare SonarQube Analysis"
          inputs:
            SonarQube: 'Sonar-integration-register-front-end'
            scannerMode: 'MSBuild'
            projectKey: 'OfqualGovUK_ofqual-register-frontend_AZKvU5DXb83dXmjjBi1u'
            projectName: 'register'

        # PowerShell script to modify SonarQube parameters
        - task: PowerShell@2
          displayName: "Modify SonarQube Parameters"
          inputs:
            targetType: 'inline'
            script: |
              if ($env:BUILD_REASON -eq "PullRequest") {
                  $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.pullrequest.*":"[\w,/,-]*"\,?'
              } else {
                  $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w,/,-]*"\,?'
              }
              Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"

        # Run SonarQube analysis
        - task: SonarQubeAnalyze@5
          displayName: "SonarQube Analysis"

        # Publish SonarQube results
        - task: SonarQubePublish@5
          displayName: "Publish Results"
          inputs:
            pollingTimeoutSec: '300'

      # Audit job: This job audits dependencies for vulnerabilities.
    - job: Audit
      displayName: 'Audit Dependencies'
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: Bash@3
          displayName: Check NuGet vulnerabilities
          inputs:
            targetType: 'inline'
            script: |
              dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
              echo "Analyse dotnet list package command log output..."
              if grep -q -i "critical\|high" build.log; then
                  echo "Must fix security vulnerabilities found on the log output"
                  exit 1
              else
                  echo "No critical or high severity vulnerabilities found."
                  exit 0
              fi
- stage: Test
  displayName: "Unit Tests"
  dependsOn: BuildArtifact
  jobs:
    - job: Unit
      displayName: "Unit tests"
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Run unit tests'
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'
            arguments: '--no-build --no-restore --filter Category=Unit'
            testRunTitle: 'Register-Frontend-Unit-$(Build.BuildId)'

# Playwright Tests stage: This stage runs Playwright tests.
- stage: PlaywrightTests
  displayName: "Run Playwright Tests"
  dependsOn: BuildArtifact
  jobs:
    - job: RunPlaywrightTests
      displayName: 'Run Playwright Tests'
      pool:
        vmImage: $(vmImageName)
      steps:
        - script: |
            pwsh Ofqual.Common.RegisterFrontend.Playwright/bin/Debug/net8.0/playwright.ps1 install --with-deps
          displayName: 'Install Playwright browsers'
        - script: |
            dotnet run --project Ofqual.Common.RegisterFrontend.csproj --urls "http://localhost:7159" &
            sleep 10
          displayName: 'Start Server'
          env:
            RegisterBaseUrl: $(RegisterBaseUrl)
            DefaultUrl: $(RegisterBaseUrl)
            RegisterAPIUrl: 'https://ofq-dev-apim-register-api.azure-api.net/'
            StorageContainerUrl: 'https://saofqregisterdev.blob.core.windows.net/'
            RefDataAPIUrl: 'https://ofq-dev-refdata2-fuasa5gxhfdhh4dd.ukwest-01.azurewebsites.net'
        - script: |
            dotnet test
          displayName: 'Run Playwright tests'

- stage: DockerBuild
  dependsOn: 
    - BuildArtifact
    - StaticAnalysisAndAudit
    - Test
    - PlaywrightTests
  displayName: Docker Build 
  jobs:
  - job: Build
    displayName: Build 
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          latest
          $(tag)

- stage: Healthcheck
  displayName: "Health Check"
  dependsOn: DockerBuild
  jobs:
  - job: HealthCheck
    displayName: "Health Check"
    steps:
    - script: |
        docker run -d --name register-frontend-healthcheck -p 8080:80 $(imageRepository):$(tag)
        echo "Waiting for container health check..."
        for i in {1..10}; do
        HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' register-frontend-healthcheck)
        echo "Health status: $HEALTH_STATUS"
        if [ "$HEALTH_STATUS" == "healthy" ]; then
            echo "Container is healthy!"
            exit 0
        fi
        sleep 5
        done
        echo "Container did not become healthy in time."
        exit 1
      displayName: Health Check

    - script: |
        docker stop register-frontend-healthcheck
        docker rm register-frontend-healthcheck
      displayName: Cleanup Healthcheck Container
      condition: always()

- stage: ContainerVulnerabilityScan
  displayName: "Run Container Vulnerability Scan"
  dependsOn: Healthcheck
  jobs:
  - job: InstallTrivy
    displayName: "Install Trivy"
    steps:
    - script: |
        echo "Installing Trivy..."
        # curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        # export PATH=$HOME/bin:$PATH
        trivy --version
      displayName: 'Install Trivy'

  - job: RunTrivyScan
    displayName: "Run Trivy Scan"
    steps:
    - script: |
        echo "Running Trivy Scan..."
        export PATH=$HOME/bin:$PATH
        trivy image $(imageRepository):$(tag) --exit-code 1 --severity HIGH,CRITICAL
      displayName: 'Run Trivy Scan'


- stage: Push
  displayName: Push
  dependsOn: 
    - ContainerVulnerabilityScan
  jobs:
  - job: Push
    steps:
    - task: Docker@2
      displayName: Push Image to Container Registry
      condition: succeeded()
      inputs:
        command: push
        repository: $(imageRepository)
        ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/releases') }}:
          containerRegistry: $(dockerRegistryServiceConnectionProd)
        ${{ else }}:
          containerRegistry: $(dockerRegistryServiceConnectionDev)
        tags: |
          latest
          $(tag)

