trigger:
- dev  # Trigger pipeline on changes to the main branch
variables:
- name: DOCKER_BUILDKIT
  value: 1
pool: ofqual-agent

stages:
  # - stage: Build
  #   displayName: Build Stage
  #   jobs:
  #     - job: BuildJob
  #       displayName: Build Job
  #       steps:
  #         - checkout: self  # Checkout the repository
          # Set environment variable for .NET Core SDK task
          # - script: echo "##vso[task.setvariable variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE]true"
          # - script: echo "##vso[task.setvariable variable=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT]true"
          # - script: echo "##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT]true"
          # # Use .NET Core SDK version 8.x
          # - task: UseDotNet@2
          #   displayName: 'Use .NET Core SDK'
          #   inputs:
          #     version: '8.x'

          # # Restore dependencies and build the application
          # - script: |
          #     dotnet restore
          #     dotnet build --configuration Release
          #   displayName: 'Restore and Build'

          # # Run tests
          # - script: dotnet test --configuration Release --no-build
          #   displayName: 'Run Tests'
  - stage: Build
    displayName: Build and push stage
    jobs:  
    - job: Build
      displayName: Build job
      # pool:
      #   vmImage: 'windows-2019'
      steps:
      - checkout: self  # Checkout the repository
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: 'bolaacr.azurecr.io/frontend'  # ACR and image name
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile
          containerRegistry: 'cgi-acr-connection'  # ACR name
          tags: |
            $(Build.BuildId)




  # - stage: Dockerize
  #   displayName: Dockerize Stage
  #   jobs:
  #     - job: DockerizeJob
  #       displayName: Dockerize Job
  #       # pool:
  #       #   vmImage: 'windows-2019'
  #       steps:
  #         - checkout: self  # Checkout the repository
  #         # Log in to Azure Container Registry (ACR)
  #         - task: Docker@2
  #           displayName: 'Login to ACR'
  #           inputs:
  #             command: 'login'
  #             containerRegistry: 'cgi-acr-connection'  # ACR name
  #             containerRegistryType: 'Azure Container Registry'
  #             azureSubscription: 'ofqual-service-connection-bola'  # Azure subscription
  #         # Build and push Docker image to ACR
  #         # - task: Docker@1
  #         #   displayName: Push Docker image
  #         #   inputs:
  #         #     command: Push an image
  #         #     containerRegistryType: Azure Container Registry
  #         #     azureContainerRegistry: 'cgi-acr-connection'
  #         #     imageName: 'frontend-image'
  #         - task: Docker@2
  #           displayName: 'Build and Push Docker Image'
  #           inputs:
  #             command: 'build'
  #             #command: 'buildAndPush'
             
  #             repository: 'bolaacr.azurecr.io/frontend'  # ACR and image name
  #             dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile
  #             containerRegistry: 'cgi-acr-connection'  # ACR name
  #             azureSubscription: 'ofqual-service-connection-bola'
  #             tags: '$(Build.BuildId)'
               

  # - stage: PushToACR
  #   displayName: Push to ACR Stage
  #   jobs:
  #     - job: PushToACRJob
  #       displayName: Push to ACR Job
  #       steps:
  #         - checkout: self  # Checkout the repository

  #         # Docker login to Azure Container Registry
  #         - script: |
  #             docker login -u $(ACRUSER) -p $(ACRPASS) $(ACRSERVER)
  #           displayName: 'Docker login to Azure Container Registry'

  #         # Push Docker image to ACR
  #         - task: Docker@2
  #           displayName: 'Push Docker image to ACR'
  #           inputs:
  #             command: 'Push'
  #             repository: 'bolaacr.azurecr.io/frontend'  # Replace with repository name
  #             #dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile
  #             containerRegistry: 'cgi-acr-connection'
  #             azureSubscription: 'ofqual-service-connection-bola'
  #             tags: '$(Build.BuildId)'
               
  #         # # Log in to Azure Container Registry (ACR)
  #         # - task: Docker@2
  #         #   displayName: 'Login to ACR'
  #         #   inputs:
  #         #     command: 'login'
  #         #     containerRegistry: 'acr-connection'  # ACR name
  #         #     containerRegistryType: 'Microsoft.Container.Registry/Registries'
  #         #     azureSubscription: 'ofqual-service-connection-bola'  # Azure subscription

      - task: Docker@2
        displayName: 'Login to Azure Container Registry'
        inputs:
          command: 'login'
          containerRegistry: 'cgi-acr-connection'  # ACR connection name      
      - task: Docker@2
        displayName: 'Pull Docker image from ACR'
        inputs:
          command: 'pull'
          repository: 'bolaacr.azurecr.io/frontend'
          tags: 'latest'

      - task: AzureRmWebAppDeployment@4
        displayName: 'Deploy to Azure App Service'
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'ofqual-service-connection-bola'  #  Azure subscription connection name
          appType: 'webApp'
          WebAppName: 'ofqual-register-frontend'
          DockerImageName: 'ofqual-register-api'
          DockerImageTag: 'latest'